apiVersion: v2
name: infrastructure-stack
description: Core Controllers (KEDA + Cert-Manager)
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  # KEDA: The Event-Driven Autoscaler
  - name: keda
    version: 2.14.0
    repository: https://kedacore.github.io/charts
  
  # Cert-Manager: The Identity Factory
  - name: cert-manager
    version: v1.14.4
    repository: https://charts.jetstack.io