---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datadog-secret
  namespace: monitoring
spec:
  encryptedData:
    api-key: AgArmregQSsGrog5R38nkV0Eoy0E2B5bkIYFlmjKVsa/zxxkCF7j9cIPBfTsgrLORFjzB9G4mOfmfniny0T06gGlPNxmv56sgcLbRiSmhNA7VslS2QrIEClax3MiIYJC4+So+VP8kiIl+AFhMhgP/TfySf9gic/2BfAIFob6UMh3t8DXhNPm5RF/EuTnQzGYsrgZjehuMWhcGjlahJusxdt5FA7mn+4UWme61IyF1SGpPlepmkS1KWzr4QzmCNBggHBkQcXpLuPMk+kyBoRI6FW4rMvWPUKDwU1pVz4LCdG8m3+Iz21p5AXbcMvI0ZrzqJ5DJ8IEFIvFTUJtKqXxi3cXi7iPPxgwGy8zzQM1/llvufP6ezcFXlBsGyp1JNyg7F/bXRvVzQY+0uOxY+Fn5MS4bTI0hWdiA8q1WKvCvlqJX7JWOKRcyJP8YUw1kbdpiza9KX8knFdfw7etzqUogm7HBVubVEYLJsbDiYH2wjykcB42Kank5Jp7LT1FRlnmDzLosaNcZ/YmGmjX15O4GGn9bTKwjYQEZS9ZHMUpgWoLGYlFR+/uNSrNE3yTtrjAn/BWJDYELT+WllwI4XqV4FsL8uZPBoc0mUeQur+WVtSJ7pO41hURL1hnsDLWsvu4qf/UDL25bAj3PTdHJQAp5QvHV8KpBn71mVknawgVtquzP9ee4zYgDI9OJE57fzf4odwWa+UCWixXru8r0t7Jpe3ggUr3K0Iw/PSP+IjlgYTlGg==
  template:
    metadata:
      name: datadog-secret
      namespace: monitoring
