---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBm/f6yOasN5Gm/bupUlQqL1xNulAh2+V2d9j79zCVVbq9RMy7pXjkcWgPEa6KEmWEDD00UJX7YYx3z1XNtpaFPWqwhyeiCyO7KWFMmfPGOWvJaiY/hjSKwRF2MuNlE9W4JEvKDk7UrNzRnlzpCunKIdd7QLkHKPjdU4d3Lgnv3znDR2Ngj0o0WfsUkKCsEVst0MUJCdeLIZYMf9ELiU4Tz8v7TxMwcvNqaZGYfL2Yhr0tB1FCNVysKQ8VaSsuHsJyOvO8vgyh3rsft82sk2y7LjbUH5kYeP/yP48G5FbL5R+5I03/hwKjp58XwfnAHzGOi2ECGJcUsqJSO5KOSvm8y783sbpY/CsQfo5Vm/SZGL4b9vnwk4DLV3TT4lpBNUUxcriZZPzyX+/h9BsOn8wG31MjWjeqo+vtdNCG7t2j0tQLZMJNH3v0U9DQYeCtELvxTbWE1wiiezf153jBIk59AvsjeIQGObdIIPBhBJpRMKy43o5O0cHQYOTMOKx9UTGBq0QhjdmpL48kTX7+NC0g1251Oe8TX+LSQ0/iezYpbmE4EJLQ0l+kYWm+0o/+BN8YvHC1bKf7JSbbB0rV0XrFx/1qfTVaXyC23/HBj4dPW0L1bCRxRivDj+WfIh/cMdQiylCLT4DtQr5teD84BKt3gZRfZUCo58ezssD1FERFWEjf9ts0TNloG5u2Ryr3CkQY9D9rIa7XbBRnDsLo=
    admin-user: AgANbUtT4ebDsU6USj9K9jdNBAg4onc9EzlQGVm84DD3QGaR60oFNXsWKDPPiO7BFnDL8br3vQFxorlQ7LBAQWh6ncQHEWBWNkK2jprad5bBIxFO1HTXyGlPmqo1OVnQJFNkWy19i9g/5sbMrbEAUcaS0QQCklv+pIk4G/NHBlVRNJbsdNiNy7+0rbqdB16pCPeVDQ3clZGNUDgNhxJRKkZdz7wp+Y5YaBmVnmHXNDjeHRIHKANSpak97SZCDQtwVUvWEF5FBpf72IblP0nD6C3LLteTMT/Cp1d07ti8hpPtUrGv0f2cSpQ8DKdDC8T4l9dGQqZEHxhcm7Vg32xe5pvdDXmuC4SMmZltTeF1HNcQJK4boGyd+VdpMO1UyrWJ4e/OYlp4o+bBekbcv2Ri+5fr4MEduVUBqvWNr735ArIIeTyqaRiZn6NHURKa8q3YWlxDIqQvQsYMHolSotLgZnmvinENo6apbgUzb27uzAQIo2kMAwRqebtqt4OHstgd0F/e3tBcycbw5zjBqM5J4AKjmZnEpNIpH6tVIQexxd3cD8TnPlQCV4G70KDx54fK6DXj6rhQKbPK8JF3++osoZ1pxFTT3xUMJBaVX5VYt1iat+3Ivjpo0QwiGaP8EwCqx6lQ/Zi+GZ2FLneqUNiXfM8rM9AEmINpGH9yJtJx6VocclZHT9UfUfrYOk9VnLn3kbYKQUuzfA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
