{{- if not .Values.cloudflare.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: study-buddy-ingress
  annotations:
    # Rewrite /api/v1/upload -> /upload
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: cilium
  rules:
  - host: {{ .Values.config.cognitoDomain }}
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: study-buddy-backend
            port: { number: 80 }
      - path: /
        pathType: Prefix
        backend:
          service:
            name: study-buddy-frontend
            port: { number: 80 }
{{- end }}