---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keda-aws-creds
  namespace: study-buddy
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgA1aa1gMuOQD8XqBFYso+nzYrAPcnlAPrM5E0z0bcJ8t0qkRtLBpLoTmeWE+mXFkXEEpX9IPpTkfgFg2bbUaBNAbI3KxRak27IbCZ1tw+4D9RGtbxFyhTtFn3VVXU85YIfX4OtjDyVj3fzaywYWwBH1xdKoZPq1eFh6nnZeBhoY7JFMXN8VdIEqftLPst7JpataCohZx1tEAUee97/36L7sdu/lm7+rold9wdfRfL2Jrg1jnUKULTTwq39MgwgAyctoYekeYG7IeK2U0CZs5FOEUNE5OPx1EA3LXUe7L5SmwvdHldZAcywlLJhvqceUbggVWPpF6gn73ljEKOh7UJzJ1jYqcpqeKehRV3NTx23iKC3DscFAvXwSDnoUmUDz0bI+pDJ2n2zGxnpJIDxjoWzgrH+IVNiddHQtqVPyqUnEnlAKYgjQbbuqp/IE+6hqnYlyhP+xGwF6g4jsnxO0TBp4T1R4hJuoZpi5Z0GZbbEQjpWBvR+MYflfeM+8IsTIq+A8gOyyd7KHBt3V5wvU4KzBJNV4OYnXt9OZ7MCxGviLG5PiFXH3RN3PtNa15OAmCtiCbrOx7D/Ux3xQjYUhZhpY1IWYqZWmXjK5ksTUjdtzkoE0PdAg4a2aIEizcaipslKba9eZrtEgr+6R7wDxzJecA9oK7E18QRSXWiui9pr/DQKZXrn65PDX3Cb3v2djUv418gb26MZJH2n82G0HDoNg5+X75g==
    AWS_SECRET_ACCESS_KEY: AgCm24V61nd7jNOYS2/7MvfSSsAioL5leE0yG2N3Lm58zoWUQiZc+SLoaSIKVLB53NQfFosZct3rmLMVMVoHRV4+g5ex6FPCqp9oLxcc2/vCspolwCCb0tTmzMVzgzL9TPqnYi8UaIUzMmIy0byScR2GtNKDdqREirZ/t/uUQa+sDPLM8VOw9dCfjMzw0RMAjpHe6MYOvxe+k3q/ss/JEPyZJ8Xwm4Ys+KwQh3+Vpeg1j9yQHwY7e0fdtltqr5pmuvVVp5pRH18oPFhW7HzESDYc4P3SGtRLmr5NnmbRbXmBMeQAsDaU6ayw7Agviwm+Ez+Mamo+C7w6ppRCbw12f7MXZTbk/ZwWaJjmRC2t7loFYgj6fJ9FKbca3cVKyEhd8KdYmizxfrUdOMQkPU/6c4gRnLO3ds1BOvBZ5UMK1J4pCyqV8XQ4dfX4mRZ301X3fIUCiXHzZ1SnWbizdd7Ew1AN1e1VH29wU9kdl1jOIXEyBKekAh8NOoscycn6XEVc4Ztl44AZVPH7OT5y+pSHglH/CzubRNDWTKHkKpSj5zfM/uqvFAtlyA0SBwOgouF6PrtboOjzQzyDR72P6CCMnTzh8VN4e8b9tmfMpJfSr1Y8FaL49hKUZZSMKFjuEcl4NF890+r6fvy1ylf5kYB/Q6VbHv9kRYzlGmR5CWGk017jltnB1s8mEgDzHVH3LgarIw2J74OJ/QDqZZB4BgA2rguWD8MhVu1YYo/59PRHtcfTxmSYDrmmU6em
  template:
    metadata:
      name: keda-aws-creds
      namespace: study-buddy
