{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "keda-aws-creds-temp",
    "namespace": "study-buddy"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "keda-aws-creds-temp",
        "namespace": "study-buddy"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "AWS_ACCESS_KEY_ID": "AgCD+zkUO807OwNyjOhVImq6FIfnfYjiptK4M1zzaSbfLORjLd+RsDN2+chBQ8tmSF5ZVdR1qW+m/OQ6xxbGpzbqEGaOhnU75nJK8hAsdccCV+t/lFS24KKTRaAidj3qPZ4ZPCh5VqnE7wEejKsBBIDyf200vMwmXrMnD2jKFNl8iBAEQXkQGMWSTxHW8pfLl+WhFibBAAxZH2xzP0UEpnBoUbTDGoEYL4xAl0bID6yt0zlbu3caOLPJdFCJjf/s/ccbQLXZm1J+oGep9EnxGtkT5XQIvybRkCxPZKXDZ8IAL9pw3ZEhScqBFaf3SY602Vl9k+4QRXidhYHCZNBiPr8s6ILolQqmn/lwprcsVhPIzoVca8jLn6+Rfo4qy3rlS8zdoGrDh1N+TPj3cpw8tV5PQvyuoG2dU7u/0zf5SosRCpDk9He8IXrnjaIGcrtpC1IM850PVFmAwXP4pnnZJcEjUVzuAIhHxAi52slOeIkBcaPtYb0ddsVsszs0pH4+zJeLxjuRqAqpwDDKvkAJp20vIERxuWDm+Uioq8vHrI1IcOiOY518WtyEHwK1ErVeZJy4tncILgjd9Y7Ogf4fTqkJ1KYe34Ffh6ruKdywnWTDHwvRZWbecWoi7kQdc3q4Pw4yD6GmX3pZsOYnLb5ZWWgJWFEa7Raj1GnGZrQbeZGjb/xYm7k/XzF5PSBpn6BpfbO7XB1zRROf4nmnOfaklK0=",
      "AWS_SECRET_ACCESS_KEY": "AgBKL4Q5AIKxPfrXjmxCMjxRFGPTgoJ5Nb5FqxU/JQp4XS5P9jqsGk0/aQyR5ETNA/G7bNGOJpeTz/v3sjTp9LiruGjVKp56NnN6ZIy3VH8ENP/8Twsd5u9N8F5VQ3bErXXAb4ATpMa71dBaujD8tte/7PemacQJrr1pQ+9poLnrTNpHWcxCYC5dJeHDNrhqYgUEpMeZOnCamdOE3/17z5EgPIdL8yFnsOsN3YjpqFADSISuBbwIseLbwaPKmwYWyJ+dcF9uRQOaPdF34u/tYzjg2bLiDdvCoRg5xrkhawSAlteafZH2NAUMGKuCFRtCFgO35AGhNg+iZT5dDgU9HR0tyBWo0DOVZJye4oeKrdOX16u2l2Gfp7AoCnV9rMkfAuvyP+Sr8IG83fZuceuRwb1OP9Gsi5li+joY+LqcNrJ4VOxqBl7ef+eepicWV0Qh9iuC5godf/7KDCM1kRx7hbXJaHFej2jNOT0JUPE/Zs735eKSPYRTpTy1uPmlhBybby8kgXGpuocPl9hYibYiJ3luKQFeyLZRiQRjcHNYe/aluYm++c0udM0xpVJuJsfmojPB+S6qhbXC1HCcK5AGIhnr3LmMjANMc6GUog+secPg59t8QADyPj2UIGlCariZBIqhW04LySDFqdYi0d61OAi7BaCHEnuyPTMguQnWM0Mm2nIj18LsjizDjtHZ0dCfQ83A4snFJRDY5kbegEiZyva6vgO+T09Usl8sUlzKCdA="
    }
  }
}
